### ISSUE TITLE
Match colors on top and bottom charts when multiple files to tags are plotted in same chart

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HistogramLogAnalyzer#5]
Currently, when multiple (e.g. 5) files are selected and plotted in the same chart, the color choices for the lines in the top (time based) and bottom (percentile based) charts are not the same: Different colors will be chosen for the different charts and each has a separate color legend.

We should change this to use a single legend and match the colors across the bottom and top.

**Comment by dimitryc** [comment]
Fixed by commit
https://github.com/HdrHistogram/HistogramLogAnalyzer/commit/3ee0f80f7160448a1296d674ce0a15d5a058b62b
